workflows:
  cordova-ios-build:
    name: Cordova iOS Build
    environment:
      xcode: latest
      node: 18
      vars:
        BUNDLE_ID: "com.yourcompany.parichayapp"
    scripts:
      - name: Install Cordova
        script: |
          npm install -g cordova

      - name: Clean Existing iOS Platform (optional but recommended)
        script: |
          if [ -d "platforms/ios" ]; then
            cordova platform remove ios
          fi

      - name: Install cordova-ios explicitly
        script: |
          npm install cordova-ios@latest

      - name: Add iOS Platform
        script: |
          cordova platform add ios

      - name: Prepare Cordova App
        script: |
          cordova prepare ios

      - name: Build Cordova App
        script: |
          cordova build ios --release

    artifacts:
      - platforms/ios/build/**/*.ipa
