workflows:
  cordova-android-build:
    name: Cordova Android Build
    environment:
      vars:
        BUNDLE_ID: "com.yourcompany.parichayapp"  # Replace with your actual package name
      node: 18.16.0
    scripts:
      - name: Install Cordova
        script: |
          npm install -g cordova

      - name: Clean Existing Android Platform (optional)
        script: |
          if [ -d "platforms/android" ]; then
            cordova platform remove android
          fi

      - name: Add Android Platform
        script: |
          cordova platform add android

      - name: Prepare Cordova App
        script: |
          cordova prepare android

      - name: Build Android App (Release)
        script: |
          cordova build android --release

    artifacts:
      - platforms/android/app/build/outputs/**/*.apk
      - platforms/android/app/build/outputs/**/*.aab
